CREATE DATABASE IF NOT EXISTS website;

CREATE TABLE IF NOT EXISTS US3R(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	first_name CHAR(25) NOT NULL,
	last_name CHAR(25) NOT NULL,
	email CHAR(60) NOT NULL,
	phone BIGINT NOT NULL,
	password  CHAR(80) NOT NULL,
	adminRights BOOLEAN DEFAULT 0,
	PRIMARY KEY (ID),
	UNIQUE (email, phone)
);

CREATE TABLE IF NOT EXISTS PROPERTY(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	ownerID BIGINT NOT NULL,
	listingType CHAR(15) NOT NULL,
	country CHAR(30) NOT NULL,
	city CHAR(30) NOT NULL,
	street CHAR(30) NOT NULL,
	streetNumber INT(4) NOT NULL,
	firstPublished DATE NOT NULL,
	lastPublished DATE NOT NULL,
	state CHAR(10) NOT NULL,
	price INT NOT NULL,
	area INT NOT NULL,
	floor INT(3) NOT NULL,
	numberOfFloors INT(3) NOT NULL,
	constrYear INT(4) NOT NULL,
	bathrooms INT(3) NOT NULL,
	photo CHAR(50) NOT NULL,
	comments CHAR(200),
	PRIMARY KEY(ID),
	FOREIGN KEY(ownerID) REFERENCES US3R(ID)
);

CREATE TABLE IF NOT EXISTS RESIDENTIAL(
	rpropertyID BIGINT NOT NULL,
	rooms INT(4) NOT NULL,
	FOREIGN KEY(rpropertyID) REFERENCES PROPERTY(ID)
);

CREATE TABLE IF NOT EXISTS COMMERCIAL(
	cpropertyID  BIGINT NOT NULL,
	commercialType CHAR(25) NOT NULL,
        FOREIGN KEY(cpropertyID) REFERENCES PROPERTY(ID)
);

CREATE TABLE IF NOT EXISTS FAVOURITE(
	userID BIGINT NOT NULL,
	propertyID BIGINT NOT NULL,
	FOREIGN KEY(userID) REFERENCES US3R(ID),
	FOREIGN KEY(propertyID) REFERENCES PROPERTY(ID)
);
